# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Build with yarn
      run: |
        cd src/frontend
        yarn install && yarn build:dev && yarn public
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: frontend
        path: src/frontend/frontend
  
  agent-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Use golang env
        uses: actions/setup-go@v1.0.0
      
      - name: build agent
        run: |
          ls
          
        # cd src/agent
        # sh build_linux.sh
          
            
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: agent
          path: src/agent/bin/*
  
